# Site settings
title: Philip in Seattle
description: >
  This is Philip's blog. Thanks for stopping by.
baseurl: "" # the subpath of your site, e.g. /blog/
gravatar_hash: '577b0958320b7fccef0b13017933558f'
url: "https://philipmw.github.io"
github_username:  philipmw

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed