# Site settings
title: Philip in Seattle
#email: philip@mailworks.org
description: >
  I am Philip. I live with my wife Sue in Seattle.
  Thanks for stopping by.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://philipmw.github.io"
twitter_username: philip4g
github_username:  philipmw

# Build settings
markdown: kramdown

gems:
  - jekyll-feed